### ISSUE TITLE
duplicate if-elseif-else in ImageStreamIo.c

### ISSUE THREAD

**Issue by drbitboy** [milk-org/ImageStreamIO#25]
https://github.com/milk-org/ImageStreamIO/blob/c4b3c531f4653f3b570345f43b2686cd25af0db8/ImageStreamIO.c#L698

https://github.com/milk-org/ImageStreamIO/blob/c4b3c531f4653f3b570345f43b2686cd25af0db8/ImageStreamIO.c#L818

The second else-clause should be redundant, and would never be reached because of the first, if the first had the ```return FAIL;``` that it should have; as it is now, the lack of that return near the first else-clause leaves an open file descriptor (cf. [here](https://github.com/milk-org/ImageStreamIO/blob/c4b3c531f4653f3b570345f43b2686cd25af0db8/ImageStreamIO.c#L744)) when it exits .

I would think the best fix would be to do a ```if (location < -1) { ImageStreamIO_printerror(...); return FAIL; }``` at the beginning, and then the rest of the code in that routine need only check ```if (location > -1) { <GPU mem stuff>; } else { <CPU mem stuff>; }```

**Comment by oguyon** [comment]
fixed in commit d6f9c28a7cbc7b9a80c30cdd6a33a109697b4961
