### ISSUE TITLE
sem_unlink argument should be semaphore name, not semaphore filepath

### ISSUE THREAD

**Issue by drbitboy** [milk-org/ImageStreamIO#29]
https://github.com/milk-org/ImageStreamIO/blob/d6f9c28a7cbc7b9a80c30cdd6a33a109697b4961/ImageStreamIO.c#L1634

See issue title.

**Comment by drbitboy** [comment]
Same for this line:

https://github.com/milk-org/ImageStreamIO/blob/d6f9c28a7cbc7b9a80c30cdd6a33a109697b4961/ImageStreamIO.c#L1179

**Comment by DasVinch** [comment]
Closed throughout unnamed semaphore upgrades.
