### ISSUE TITLE
Semophore usage

### ISSUE THREAD

**Issue by a-sevin** [milk-org/ImageStreamIO#3]
Hi,

I want to introduce a discussion on the semaphore usage.

In the ImageStreamIO functions, semaphores are used to block consumers but if the producer runs faster than the consumer, the number of tokens will increase and it will not block the consumer anymore.

The consequence is you need to implement 2 thinks:

- the producer; check if the value is < to SEMAPHORE_MAXVAL before post a new token
- the consumer: check if the flag md->write is 0

Possible solutions are: 

- using modern C++ implementations with mutex and condition variables in SHM (complex solution but more portable on various architectures)
- using functions to handle the lock mechanism:
  - lock: reset all semaphores to 0, but the flag md->write is 1
  - unlock post all semaphores to 1, but the flag md->write is 0

What do you think?

Arnaud

**Comment by oguyon** [comment]
Arnaud,

Good point.


We should implement solution 2 (functions to handle lock mechanism), and as you point out it would clean up code. I propose we start with that, and I'm happy to code it unless someone volunteers (you?).

Solution 1 may be a longer term goal - it would require changing the stream data structure.
Would it require writing/compiling the corresponding function(s) in C++ ? I assume this could also all be handled in a single function (or a few functions) - is this correct ?

I'm not sure how mutex would replace semaphores. Mutex are originally designed for exclusive access to data, which is not what we're trying to achieve here. How would that work ? 
The current semaphore implementation in milk also supports values >1, which is <mostly> useless with one exception: we can monitor if a consumer is lagging behind a producer by monitoring the semaphore value. Would we loose this if using mutex.
... I basically don't know enough about your proposed solution 1 to say anything clever/useful about it.

While we're on this topic:
We currently don't have a clean way for programmers to keep track of which semaphore is allocated to which consumer. We're currently asking programmers to carefully keep track of this, but it's all too easy to have two processes waiting on the same semaphore (I've done this many times). I've been wondering how we could implement some sort of exclusive sign-up for semaphores (function asking for semaphore channel, returns channel to use), but this has its own challenges (what if the consumer crashes/terminates before releasing semaphore channel) ? Should we "force" programmers to use signal handling / atexit to release semaphore when process is killed ?
All: any thoughts / ideas on this ?

Olivier

**Comment by a-sevin** [comment]
Hi,

At this time, for the solution 2, there is no emergency, so the first one who find a free slot, code it.

You are right on the solution 1, you need to rewrite a part of the data structure but this part is only used in ImageStreamIO (I think). You can easily recode ImageSteamIO as a C++ library with the benefits of template and the rest of MILK can stay in C.

For mutex, you are right, the are designed for exclusive access to data, it's why you add condition variable (CV) to assure the synchronization. For the case of multiple consumers, CV can notify only one consumer (the first who takes the notification) with notify_one or notify_all which unlocks all the consumers. http://thispointer.com/c11-multithreading-part-7-condition-variables-explained/

For your last idea, in pure-C, it's quasi-impossible, I think. A way to reserve a sem slot for a consumer can be a vector of char*. When a consumer reserves a sem, it puts its name at the same index (clear enought?). In C++, there are more powerful tools, you can use a map to index a vector of semaphore with a string. You can also put guards on objects/pointer to handle ungraceful exit for example and assure that the consumer unregister itself.

Arnaud
