### ISSUE TITLE
GPU-compatible image stream

### ISSUE THREAD

**Issue by oguyon** [milk-org/ImageStreamIO#4]
Data format should support GPU-hosted memory locations. Need to address synchronization issues. NVIDIA's managed memory is a model, but it suffers from sub-optimal performance because it forces synchronization between GPU and CPU memory even when not needed.

**Comment by a-sevin** [comment]
Actually, I'm thinking on the implementation of this feature and there are, at least, 2 possibilities:

Solution 1: put all the IMAGE structure in the GPU memory
Solution 2: put only the array and add cudaMemHandle in the image

Pro:

Solution 1: have an access to the KW and METADATA directly in the GPU
Solution 2: easier to implement less memory footprint in the GPU

Con:

Solution 1: lost of the critical sem functionality as the sem is stored inside the GPU
Solution 2: GPU can not access to METADATA like counters

Maybe, what we can do is to keep everything on CPU and add a location attribute and put only IMAGE and METADATA in the GPU

any comments?

**Comment by oguyon** [comment]
I vote for option 2 (at least initially)
I like your last suggestion: keep structure on CPU but allow for the image array to be located on either CPU or GPU.

This scheme can also support multiple GPUs: a variable in the metadata would indicate on which GPU(s) the data is.

We would provide functions to move data from/to CPU/GPU, and it would be quite straightforward to make these memory copies automatic by looking at the values of the memory flag(s)

**Comment by a-sevin** [comment]
I agree with you
To be honest, I already started to implement the solution 2

**Comment by a-sevin** [comment]
Beta version of GPUIPC  at f96c03a 
I didn't do yet any non-regression tests.

You can to a try by compiling CACAO with -DUSE_CUDA=ON and compile ImCreate_test_gpuipc.c and ImCreate_test_gpuipc2.c (you can modify make_gpu_tests.sh to compile it)

execute first _ImCreate_test_gpuipc_, it creates a GPU SHM and put some data on it then waits a semaphore. Then execute the _ImCreate_test_gpuipc2_, it reads the GPU SHM, modify it and post a semaphore which it unlocks the first one and it reads read again the SHM.

Again, be careful, I didn't do any non-regression tests

**Comment by a-sevin** [comment]
FYI, the feature branch has been tested on bench with keywords (EXPOSURE, ...) and framecounter from metadata. All process use CPU or GPU RAM buffer. I did'nt try mixed installation (using or not USE_CUDA flag)
