### ISSUE TITLE
shmim data alignment

### ISSUE THREAD

**Issue by drbitboy** [milk-org/ImageStreamIO#45]
Has anyone ever looked into data alignment in the shmim?

Because the IMAGE_METADATA will probably always end, and therefore the data memory will start, on a reasonable (8-byte?) boundary.

But the length of the data memory **image->md->imdatamemsize = ImageStreamIO_typesize(image->md->datatype) \* image->md->nelements** will not; it could even be an odd byte boundary.

In addition, an odd number for image->md->sem (NBsem) or image->md->NBkw could also cause problems for later memory assignments.

I am working on consolidating the three separate sections, which calculate sizes and addresses in the shmim, to a single interface; I submitted a PR to one of those sections a few days ago (https://github.com/milk-org/ImageStreamIO/pull/44); this consolidation will remove technical debt by removing the opportunity for such mistakes in the future.

So, while I am working on this, perhaps we could also ensure that there are no data alignment issues.

**Comment by DasVinch** [comment]
Excellent idea!
Space is pretty cheap, we can push the start of the major elements (metadata, data array, keywords, circular buffer) to 8 byte (or bigger) boundaries.

With your new sizing functions that would be much simpler.

**Comment by DasVinch** [comment]
Closed with #55
