### ISSUE TITLE
ISIOWrap broken for int64/uint64 (on some architectures?)

### ISSUE THREAD

**Issue by DasVinch** [milk-org/ImageStreamIO#51]
I'm having an issue where I can't instantiate int64/uint64 Images from ISIOWrap.

it boils down to a type descriptor mismatch between what is consider "long" and "long long". in `ImageStreamIODataType PyFormatToImageStreamIODataType(const std::string &pf)` and the reverse function.

What I pass down from numpy as `pf == "l"` and `"L"` respectivelent for `np.int64` and `np.uint64`...
However... `py::format_descriptor<int64_t>::format()` is `q` and the uint version returns `Q`.

Per https://numpy.org/doc/stable/reference/arrays.scalars.html, I understand this is a variation in the spec between int and longlong... 
I think (from my very quick browsing) that this has been introduced at 1.16. It is possible that I haven't tried to make a uint64 SHM for all that time.

Oh no!

**Comment by a-sevin** [comment]
I'm in vacation with a short time to check my mail. The solution could be here: https://github.com/pybind/pybind11/issues/1908#issuecomment-583503536

**Comment by a-sevin** [comment]
when py::format_descriptor<int64_t>::format() is q and the uint version returns Q, it means you are on a 32bit linux...
But I have the same issue on my laptop... Strange...
