### ISSUE TITLE
Calling ImageStreamIO_destroyIm closes stdin

### ISSUE THREAD

**Issue by oguyon** [milk-org/ImageStreamIO#54]
image->shmfd not set when creating image, so remains at default value 0, which is file descriptor for stdin
Calling ImageStreamIO_destroyIm then closes stdin, which renders terminal unusable (stout looping)

**Comment by oguyon** [comment]
added in image->shmfd value in ImageStreamIO_read_sharedmem_image_toIMAGE 
The issue affected shmim reads, not creation from scratch
I think all cases now covered.- please double check
If you ever see you terminal going crazy, check we're not closing file descriptor 0

**Comment by drbitboy** [comment]
1) the **else { ... }** is unnecessary, as the preceding **if {...}** clause returns from the routine.

2) The assignment to image->shmfd would be better placed at the return of IMAGESTREAMIO_SUCCESS at the end of the routine.

**Comment by oguyon** [comment]
done - 0c5944820fe3decf6aa9f1d47611b0b938b3bdf6
