### ISSUE TITLE
ImageStreamIO_read_sharedmem_image_toIMAGE exit(0)'s on zero size

### ISSUE THREAD

**Issue by jaredmales** [milk-org/ImageStreamIO#6]
In `ImageStreamIO_read_sharedmem_image_toIMAGE` if the call to `mmap` returns `MAP_FAILED`, `exit(0)` is called instead of just `return -1;`.

Example problem: in a client app (say a viewer like `milk2ds9`) which is started before the shared memory is created, we want to be able to patiently wait for it.  But if you call `ImageStreamIO_read_sharedmem_image_toIMAGE` too quickly after the source app begins the creation process this will fail with `Invalid argument` due to 0 size, thus killing the client.  I have found that this is surprisingly repeatable.

Fix is simple: just change to `return -1;`

I don't want to just do this because I don't know what else it might break.  Does anything else depend on this behavior?

**Comment by a-sevin** [comment]
That's fine for me bu I don't have a global vision of all the sub-modules

**Comment by jaredmales** [comment]
@oguyon do you see any issues with switching this `exit(0)` to `return -1;'?  I've got a commit coming and can include this.

**Comment by oguyon** [comment]
no issue - go ahead. exit(0) is indeed bad.. it implies success.
Note (for later?): We should consistently use EXIT_SUCCESS and EXIT_FAILURE for portability and make code easier to read. We can also define other exit code as needed (but only if needed).
See https://stackoverflow.com/questions/13667364/exit-failure-vs-exit1



For truly portable code, EXIT_FAILURE is preferred. The C standard only defines meaning for three values: EXIT_FAILURE, 0, and EXIT_SUCCESS (with 0 and EXIT_SUCCESS essentially synonymous).

From a practical viewpoint, most typical systems accept other values as well. If memory serves, Linux will let you return any 8-bit value, and Windows 16-bit values. Unless you honestly might care about porting to an IBM mainframe, VMS, etc., chances are you don't care about most of the systems that won't support at least 8-bit return values.
