### ISSUE TITLE
tracking processes that write and read streams

### ISSUE THREAD

**Issue by oguyon** [milk-org/ImageStreamIO#9]
One current limitation of cacao/milk is that it is very difficult, when inspecting a stream, to identify which process is writing it and which processes are reading it.

This leads to several annoying issues:
- When a new process needs to connect (read) a stream, which semaphore should it pick ? There is no easy way to figure this out in an automatic way, so we currently hard-code it. This is bad practice, and prone to errors (race condition if two processes use the same semaphore). We need an automatic way to pick unused semaphores
- There is currently no easy way to map/visualize who is writing and reading streams. This makes debugging harder than it should be
- We'd like to deploy process management tools associated with data. For example, if a process that reads a specific semaphore has died, we should have a way to detect that and "free" the semaphore for other uses
(list goes on...)

I propose to add in the stream data structure the following fields:
- PID of process that writes the stream
- PID of processes that are reading the stream

When a process is writing the stream it would (re)-write its PID onto the stream.
When a process connects to a stream to read it, it would identify which semaphore(s) is available, and write its PID to the corresponding data stream entry.
A clean exit would release the semaphore by setting PID to 0.

A yet-to-be-coded manager would identify if a reading PID entry is >0 with a non-existing PID. This would be a non-clean exit that can be logged / reported to user, and the corresponding semaphore would be freed.

The additional entries would be added after line 434 of ImageStruct.h hoping it doesn't break the Python interface (except if keywords are read), but we should all ensure that our codes to read/write streams are synced to the new format.

Thoughts ?
I will wait a few days for comments before implementing the change.

**Comment by a-sevin** [comment]
It makes sense to create an array of PID and at least 2 functions: register / unregister.
In our interface abstraction layer (named Octopus), we implement on top of ImageStreamIO, a system based on circular buffer to prevent data corruption.
It can be useful to put it directly in ImageStreamIO.

**Comment by jaredmales** [comment]
This is a great idea.  We've already encountered the problem of managing semaphore-to-process allocations.  

Consider that if a process dies uncleanly, it probably is going to get restarted.  So one way to reduce the burden on the yet-to-be-coded manager is to have a way for the restarted process to know that a semaphore was already allocated for its use, and just overwrite its new PID on the restart. Is there an obvious way to add a "process name" of some sort in addition to the PID?  This could be, say, uint64_t or a char[32].

There are subtleties here though: for instance an image viewer application could have two instances running (say by two different users).  You could offload responsibility for this issue to such applications, demanding that they have their own way to unique-ify their "process name" in these scenarios.

**Comment by oguyon** [comment]
Arnaud: can you describe what the "system based on circular buffer" does to prevent data corruption ?

**Comment by oguyon** [comment]
The idea that if a process dies uncleanly some process manager would restart it scares me. I prefer to ensure that no process dies uncleanly, and if this occurs, this is a bug that needs our attention (rather than automatic restart). I worry that trying to handle unclean exit conditions (1) is challenging because we have to think about all the possible ways our programs are going to crash and (2) will encourage us to not see/fix bugs we should fix.
thoughts ?

**Comment by oguyon** [comment]
I'm in favor of keeping the image structure light (only add an array of PIDs) and moving additional capabilities in the yet-to-be-coded manager(s). Some integration with the process manager would be especially powerful.

**Comment by jaredmales** [comment]
Agree that unclean exits are not to be encouraged.  But they will happen, sometimes in the middle of the night while observing and you can't debug right away.  Some bugs happen once a week, are hard to reproduce, so you have to keep operating while debugging and live with the occasional crash.  Etc...

The logic for recognizing a previous unclean exit doesn't need to be in ImageStructIO -- that's still the responsibility of the client process.  This is just adding a 2nd component to the PID array (e.g. make it a struct with .pid and .unique_name fields) that clients can use if useful for them.

This might be the lighter-weight option in that it might not require a process manager at all.

**Comment by a-sevin** [comment]
> Arnaud: can you describe what the "system based on circular buffer" does to prevent data corruption ?

It's a simple generalization of a triple buffering to N.
[drawing](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Triple%20buffer%20Diagram.xml#R7VtRk5sqFP41eWxHxZjs4ybb3ttO2%2BnMbqd9ZRUjUxUv4ibbX38xQqKIsyZjgknzEvUAB%2Fk43%2BEcMBOwTDb%2FUJhFX0mA4oljBZsJeJg4ju06Hr%2BUktdKMrOdSrCiOBCV9oJH%2FAcJoSWkBQ5Q3qjICIkZzppCn6Qp8llDBikl62a1kMTNXjO4Qi3Bow%2FjtvQnDlhUSedTay%2F%2FF%2BFVJHu2LVGSQFlZCPIIBmRdE4EPE7CkhLDqLtksUVyCJ3Gp2n3sKN29GEUp69OABH9%2BP%2F4Cq%2FDzV%2B9X8il62LjgndDyAuNCDFi8LHuVCKwjzNBjBv3yec1neQIWEUti%2FmTzW5hnFe4h3iDe1SLEcbwkMaHb5iAMQ8f3uTxnlPxGtZLAe%2FamHi8R74AoQ5vOwdk7yLitIZIgRl95FdlAoizMzBWP69qcCVFUmy4pg8JKVjvFeyD5jcDyAFzB8LieAKXdsymY3IuAybEMwzRtwfRktYDi42UtmqUkRQonhaiGYUhSJjwvH7l4ForL8hJMzF3ifYxXKZclOAjKwgUUAp8Di%2BhA4NttsHdOtY62eyq0Zyf3iQFE81DrEz1%2Fjp7DYZAEYFw%2BcX4la42Kq3EvejdKL6rCZNyLSsdSd6P2tbpRoDHK87pR%2BwSx5QDATJ3ZqLyizIcufrlRgTXuFu0TBOFGFhwVWfOetB23P7WxvRJPOjUekNrt%2BP8yDXk2sojU9ka5RKkwmfek15ISqcia96TtpOgJXKsnnZmPSXukSigN7suN43LwMcxz7DchrRqgoLVv%2FCYMtWFPNaOWMopiyPBLU70OCtHDd4J5xzuU53ofKxXkpKA%2BEm32cLbUdO2oSj0M0hViLT3badmN%2BfiZcnTZgxczYcONKfP%2BK4gseJdvrf2eV7DdbLMv5Her8orTrGCLIpTa%2BNtVCqviq%2BPeztP1cnQnY54k2jUzz7nrWLcP5V7nDtO5yKfLnG7kO3rh251myvnsGXacjo09Dl4unY3uvCNrPpSNnen3udioS%2F9ubDyaja6lbFTNTbOxRxp66Wz07oYJS7u2EM7FRV0mfOPi0Vz0lJXReJja45Dy0qmohqnHUrHrfPlcVNTl8gdScaqjIinYMIreYPRfRXQ1BDZNdNDjdPLSia5GwEfno51He2eiOtBtHtyoPlKqt%2BJr09ku6HEQfOlcV%2BPro7PdziOSc3FdtzVx4%2FpIua7G78ZzaaDLpa%2FAfIboeVLaC29kffvx5ctfZqgyhDBmlz2O0PMIZuVtjtNVjMRytHjjYF1FeQCsHPnBiSQ1aJNae27rnQw9XVp%2BICU8ToktFxRWpITh8PWsdLA903RwlNNdu%2BenOKfjR4%2BT%2BbHww7Xn78fGEDkxN4YMlcU4QJ1k0xxxe%2BxZjIUjnupgzDNkgE2EG0MaUzw2fnR%2FthDgFzkd3ykJCh%2FRnNcsclRe9ocvFiPlACinC78GkMHapNaUaPQuSZoXSUMvzxmaiimCgaL3mWpi%2F5rab8K0yn845zhnW70p%2F0nIC%2Bd48%2B1hGijdZmWezmdclmUkL02dReX4cpTALCIUve%2By0Zrt9TXXlql1GqXOK1FSpEH5geiDpbH3AaxWSViBbnMKaKz2iE9A%2BeP%2B793V%2Fsj%2BT%2FLgw%2F8%3D)

**Comment by oguyon** [comment]
I added the PID list. There are two PID lists, one for processes that post semaphores, and one for those that wait on semaphores. Any process that uses the post/wait functions in ImageStreamIO will update the PID tables.
Next steps: write a data stream manager, write function that select available semaphore index, etc...
